addons:
  apt:
    packages:
      - libmysqlclient-dev
after_success:
  - coverage report
deploy:
  provider: pypi
  user: etianen
  password:
    secure: XW4/9HiChbPJSJe4d/MRcO+ViPGhW1iQ8kVi814KJh7mCxOAKijpW5hfdc9oSKB6d8iYB3OzZ7naIUU9GMce40bpeTgPDLVBLCSYKRNLuVoJdh+Q6ItGUiFf8kAJz5jgopG80QnCpLA9JvYxKVJ4amfYWWm204eQmIEnRRAd+Jk=
  on:
    tags: true
    condition: $DJANGO = '>=3.1,<3.2'
    python: 3.6
    repo: etianen/django-reversion
  distributions: sdist bdist_wheel
notifications:
  email: false
