sudo: false
language: python
dist: xenial
python:
  - 3.8
  - 3.7
  - 3.6
cache: pip
env:
  global:
    - DJANGO_DATABASE_USER_MYSQL=travis
addons:
  apt:
    packages:
      - libmysqlclient-dev
services:
  - postgresql
  - mysql
before_script:
  - mysql -e 'create database test_project'
  - psql -c 'create database test_project;' -U postgres;
after_success:
  - coverage report
deploy:
  provider: pypi
  user: etianen
  password:
    secure: XW4/9HiChbPJSJe4d/MRcO+ViPGhW1iQ8kVi814KJh7mCxOAKijpW5hfdc9oSKB6d8iYB3OzZ7naIUU9GMce40bpeTgPDLVBLCSYKRNLuVoJdh+Q6ItGUiFf8kAJz5jgopG80QnCpLA9JvYxKVJ4amfYWWm204eQmIEnRRAd+Jk=
  on:
    tags: true
    condition: $DJANGO = '>=3.1,<3.2'
    python: 3.6
    repo: etianen/django-reversion
  distributions: sdist bdist_wheel
notifications:
  email: false
